[package]
name = "yuri"
version = "0.1.0"
authors = ["Steve Corona"]
edition = "2018"

[lib]
crate-type = ["staticlib"] 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
md-5 = "0.9.1"
hex = "0.4.2"
libc = "0.2.80"